/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account Data */
        delete: operations["delete_account_data_v1_account_data_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/actions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Actions */
        post: operations["preview_actions_v1_actions_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Conversation */
        post: operations["start_conversation_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Conversation */
        get: operations["read_conversation_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Card */
        post: operations["accept_card_v1_conversations__conversation_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Conversation */
        post: operations["close_conversation_v1_conversations__conversation_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue Conversation */
        post: operations["continue_conversation_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_v1_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insights */
        get: operations["insights_v1_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Outcomes */
        get: operations["outcomes_v1_outcomes_get"];
        put?: never;
        /** Create Outcome */
        post: operations["create_outcome_v1_outcomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reflections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reflections */
        get: operations["reflections_v1_reflections_get"];
        put?: never;
        /** Create Reflection */
        post: operations["create_reflection_v1_reflections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reflections/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Reflection */
        post: operations["analyze_reflection_v1_reflections_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reflections/{reflection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Reflection */
        delete: operations["delete_reflection_v1_reflections__reflection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resources */
        get: operations["resources_v1_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptConversationRequest */
        AcceptConversationRequest: {
            /** Action Id */
            action_id: string;
            /** Client Request Id */
            client_request_id?: string | null;
            self_report: components["schemas"]["AffectiveState"];
        };
        /** ActionCard */
        ActionCard: {
            /** Actions */
            actions: {
                [key: string]: unknown;
            }[];
            /** Card Reason */
            card_reason: string;
            decision_preview: components["schemas"]["PolicyDecision"];
            /** Offered Message Id */
            offered_message_id?: string | null;
            /** Resource Intent */
            resource_intent: string;
        };
        /** ActionPreview */
        ActionPreview: {
            /** Actions */
            actions: {
                [key: string]: unknown;
            }[];
            decision: components["schemas"]["PolicyDecision"];
        };
        /** ActionPreviewRequest */
        ActionPreviewRequest: {
            /** Context */
            context?: {
                [key: string]: string;
            };
            /**
             * Resource Intent
             * @default reflect
             */
            resource_intent: string;
            state: components["schemas"]["AffectiveState"];
            target: components["schemas"]["TargetState"];
        };
        /** AffectiveState */
        AffectiveState: {
            /** Agency */
            agency: number;
            /** Arousal */
            arousal: number;
            /** Confidence */
            confidence: number;
            /** Emotion Tags */
            emotion_tags?: string[];
            /** Uncertainty */
            uncertainty?: string | null;
            /** Valence */
            valence: number;
        };
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Context */
            context?: {
                [key: string]: string;
            };
            /**
             * Llm Consent
             * @default false
             */
            llm_consent: boolean;
            /**
             * Locale
             * @default CA
             */
            locale: string;
            /** Text */
            text: string;
        };
        /** Conversation */
        Conversation: {
            card?: components["schemas"]["ActionCard"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Llm Consent */
            llm_consent: boolean;
            /** Locale */
            locale: string;
            /** Prompt Version */
            prompt_version: string;
            /** Reflection Id */
            reflection_id?: string | null;
            /**
             * Retain Text
             * @default false
             */
            retain_text: boolean;
            safety?: components["schemas"]["SafetyResult"] | null;
            /** @default normal */
            safety_mode: components["schemas"]["SafetyMode"];
            /** @default open */
            status: components["schemas"]["ConversationStatus"];
            /** Summary */
            summary?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ConversationDetail */
        ConversationDetail: {
            conversation: components["schemas"]["Conversation"];
            /** Messages */
            messages: components["schemas"]["ConversationMessage"][];
        };
        /** ConversationMessage */
        ConversationMessage: {
            /** Client Message Id */
            client_message_id?: string | null;
            /** Content */
            content?: string | null;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            model_run?: components["schemas"]["ModelRun"] | null;
            role: components["schemas"]["MessageRole"];
            safety_mode: components["schemas"]["SafetyMode"];
        };
        /**
         * ConversationStatus
         * @enum {string}
         */
        ConversationStatus: "open" | "closed";
        /** ConversationTurnRequest */
        ConversationTurnRequest: {
            /**
             * Client Message Id
             * Format: uuid
             */
            client_message_id: string;
            /** Text */
            text: string;
        };
        /** ConversationTurnResult */
        ConversationTurnResult: {
            assistant_message: components["schemas"]["ConversationMessage"];
            conversation: components["schemas"]["Conversation"];
            user_message: components["schemas"]["ConversationMessage"];
        };
        /** DeletionResponse */
        DeletionResponse: {
            /**
             * Auth Identity Deleted
             * @default false
             */
            auth_identity_deleted: boolean;
            /** Deleted Records */
            deleted_records: number;
            /**
             * Note
             * @default Journal data was deleted. Your sign-in identity remains active.
             */
            note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Action Counts */
            action_counts: {
                [key: string]: number;
            };
            /** Average Helpfulness By Action */
            average_helpfulness_by_action: {
                [key: string]: number;
            };
            /** Average State Change */
            average_state_change: {
                [key: string]: number;
            } | null;
            /** Completed Outcomes */
            completed_outcomes: number;
            /** Completion Rate */
            completion_rate: number;
            /**
             * Note
             * @default These are descriptive personal patterns, not causal or clinical conclusions.
             */
            note: string;
            /** Pending Decision Ids */
            pending_decision_ids: string[];
            /** Reflection Count */
            reflection_count: number;
            /** State Trajectory */
            state_trajectory: components["schemas"]["StatePoint"][];
        };
        /**
         * MessageRole
         * @enum {string}
         */
        MessageRole: "user" | "assistant";
        /** ModelRun */
        ModelRun: {
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Fallback Reason */
            fallback_reason?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * Provider
             * @default openrouter
             */
            provider: string;
            /** Schema Valid */
            schema_valid: boolean;
            /**
             * Used Fallback
             * @default false
             */
            used_fallback: boolean;
        };
        /** OutcomePage */
        OutcomePage: {
            /** Items */
            items: components["schemas"]["OutcomeRecord"][];
        };
        /** OutcomeRecord */
        OutcomeRecord: {
            /** Completed */
            completed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** Effort */
            effort?: number | null;
            /** Elapsed Minutes */
            elapsed_minutes?: number | null;
            /** Helpfulness */
            helpfulness?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Note */
            note?: string | null;
            post_state?: components["schemas"]["AffectiveState"] | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** OutcomeRequest */
        OutcomeRequest: {
            /** Client Request Id */
            client_request_id?: string | null;
            /** Completed */
            completed: boolean;
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** Effort */
            effort?: number | null;
            /** Elapsed Minutes */
            elapsed_minutes?: number | null;
            /** Helpfulness */
            helpfulness?: number | null;
            /** Note */
            note?: string | null;
            post_state?: components["schemas"]["AffectiveState"] | null;
        };
        /** PolicyDecision */
        PolicyDecision: {
            /** Action Id */
            action_id: string;
            /** Context Snapshot */
            context_snapshot: {
                [key: string]: unknown;
            };
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id?: string;
            /**
             * Eligible For Ope
             * @default true
             */
            eligible_for_ope: boolean;
            /** Explanation */
            explanation: string;
            /** Policy Name */
            policy_name: string;
            /** Policy Version */
            policy_version: string;
            /** Propensity */
            propensity: number;
            /** Recommended Action Id */
            recommended_action_id?: string | null;
            /** Safe Action Ids */
            safe_action_ids: string[];
            /** @default policy */
            selection_source: components["schemas"]["SelectionSource"];
        };
        /** PreparedAnalysis */
        PreparedAnalysis: {
            model_run: components["schemas"]["ModelRun"];
            reflection: components["schemas"]["ReflectionCopy"];
            /** Resource Intent */
            resource_intent: string;
            safety: components["schemas"]["SafetyResult"];
            state: components["schemas"]["AffectiveState"];
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Checks */
            checks: {
                [key: string]: string;
            };
            /** Status */
            status: string;
        };
        /** ReflectionCopy */
        ReflectionCopy: {
            /** Interpretation */
            interpretation: string;
            /** Reflection Question */
            reflection_question: string;
            /** Summary */
            summary: string;
        };
        /** ReflectionPage */
        ReflectionPage: {
            /** Items */
            items: components["schemas"]["ReflectionRecord"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ReflectionRecord */
        ReflectionRecord: {
            /** Context */
            context?: {
                [key: string]: string;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            decision: components["schemas"]["PolicyDecision"];
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            model_run?: components["schemas"]["ModelRun"] | null;
            reflection: components["schemas"]["ReflectionCopy"];
            safety: components["schemas"]["SafetyResult"];
            state: components["schemas"]["AffectiveState"];
            target: components["schemas"]["TargetState"];
            /** Text */
            text?: string | null;
            /**
             * Text Retained
             * @default false
             */
            text_retained: boolean;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ReflectionRequest */
        ReflectionRequest: {
            /** Chosen Action Id */
            chosen_action_id?: string | null;
            /** Client Request Id */
            client_request_id?: string | null;
            /** Context */
            context?: {
                [key: string]: string;
            };
            /**
             * Llm Consent
             * @default false
             */
            llm_consent: boolean;
            /**
             * Locale
             * @default CA
             */
            locale: string;
            prepared_analysis?: components["schemas"]["PreparedAnalysis"] | null;
            /** Retain Text */
            retain_text?: boolean | null;
            self_report?: components["schemas"]["AffectiveState"] | null;
            target: components["schemas"]["TargetState"];
            /** Text */
            text: string;
        };
        /**
         * SafetyMode
         * @enum {string}
         */
        SafetyMode: "normal" | "support";
        /** SafetyResult */
        SafetyResult: {
            /** Exploration Allowed */
            exploration_allowed: boolean;
            /** Locale */
            locale: string;
            mode: components["schemas"]["SafetyMode"];
            /** Reasons */
            reasons?: string[];
            /** Resource Ids */
            resource_ids?: string[];
            /** Support Message */
            support_message?: string | null;
        };
        /**
         * SelectionSource
         * @enum {string}
         */
        SelectionSource: "policy" | "policy_accepted" | "user_override";
        /** StartConversationRequest */
        StartConversationRequest: {
            /** Client Request Id */
            client_request_id?: string | null;
            /**
             * Llm Consent
             * @default false
             */
            llm_consent: boolean;
            /**
             * Locale
             * @default CA
             */
            locale: string;
            /**
             * Retain Text
             * @default false
             */
            retain_text: boolean;
        };
        /** StatePoint */
        StatePoint: {
            /** Agency */
            agency: number;
            /** Arousal */
            arousal: number;
            /** Created At */
            created_at: string;
            /**
             * Reflection Id
             * Format: uuid
             */
            reflection_id: string;
            /** Valence */
            valence: number;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /** Analysis Mode */
            analysis_mode: string;
            /** Message */
            message: string;
            /** Persistence Mode */
            persistence_mode: string;
        };
        /** TargetState */
        TargetState: {
            /** Agency */
            agency?: number | null;
            /** Arousal */
            arousal?: number | null;
            /** Goal */
            goal: string;
            /** Valence */
            valence?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    delete_account_data_v1_account_data_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_actions_v1_actions_preview_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_conversation_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_conversation_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_card_v1_conversations__conversation_id__accept_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_conversation_v1_conversations__conversation_id__close_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_conversation_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationTurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_v1_export_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insights_v1_insights_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    outcomes_v1_outcomes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_outcome_v1_outcomes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reflections_v1_reflections_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reflection_v1_reflections_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReflectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_reflection_v1_reflections_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreparedAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reflection_v1_reflections__reflection_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                reflection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resources_v1_resources_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_status_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
