/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account Data */
        delete: operations["delete_account_data_v1_account_data_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/actions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Actions */
        post: operations["preview_actions_v1_actions_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activity-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity History */
        get: operations["activity_history_v1_activity_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activity-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Activity */
        get: operations["read_activity_v1_activity_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activity-sessions/{session_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Control Activity */
        post: operations["control_activity_v1_activity_sessions__session_id__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activity-sessions/{session_id}/follow-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow Up Activity */
        post: operations["follow_up_activity_v1_activity_sessions__session_id__follow_up_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activity-sessions/{session_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Activity */
        post: operations["report_activity_v1_activity_sessions__session_id__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Conversation */
        post: operations["start_conversation_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Conversation */
        get: operations["read_conversation_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Card */
        post: operations["accept_card_v1_conversations__conversation_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/activity-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Activity */
        get: operations["latest_activity_v1_conversations__conversation_id__activity_sessions_get"];
        put?: never;
        /** Offer Activity */
        post: operations["offer_activity_v1_conversations__conversation_id__activity_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Conversation */
        post: operations["close_conversation_v1_conversations__conversation_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover */
        post: operations["discover_v1_conversations__conversation_id__discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue Conversation */
        post: operations["continue_conversation_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/preference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Preference */
        post: operations["change_preference_v1_conversations__conversation_id__preference_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Resources */
        post: operations["search_resources_v1_discovery_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_v1_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insights */
        get: operations["insights_v1_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/journal/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_v1_journal_entries_get"];
        put?: never;
        /** Create Entry */
        post: operations["create_entry_v1_journal_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/journal/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Entry */
        get: operations["read_entry_v1_journal_entries__entry_id__get"];
        put?: never;
        post?: never;
        /** Delete Entry */
        delete: operations["delete_entry_v1_journal_entries__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/journal/entries/{entry_id}/reflect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reflect Entry */
        post: operations["reflect_entry_v1_journal_entries__entry_id__reflect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Outcomes */
        get: operations["outcomes_v1_outcomes_get"];
        put?: never;
        /** Create Outcome */
        post: operations["create_outcome_v1_outcomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reflections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reflections */
        get: operations["reflections_v1_reflections_get"];
        put?: never;
        /** Create Reflection */
        post: operations["create_reflection_v1_reflections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reflections/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Reflection */
        post: operations["analyze_reflection_v1_reflections_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reflections/{reflection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Reflection */
        delete: operations["delete_reflection_v1_reflections__reflection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resources */
        get: operations["resources_v1_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptConversationRequest */
        AcceptConversationRequest: {
            /** Action Id */
            action_id: string;
            /** Client Request Id */
            client_request_id?: string | null;
            /** Expected Revision */
            expected_revision?: number | null;
            self_report?: components["schemas"]["AffectiveState"] | null;
        };
        /** ActionCard */
        ActionCard: {
            /** Actions */
            actions: {
                [key: string]: unknown;
            }[];
            /** Card Reason */
            card_reason: string;
            decision_preview: components["schemas"]["PolicyDecision"];
            goal?: components["schemas"]["Goal"] | null;
            /** Offered Message Id */
            offered_message_id?: string | null;
            /** Resource Intent */
            resource_intent: string;
        };
        /** ActionPreview */
        ActionPreview: {
            /** Actions */
            actions: {
                [key: string]: unknown;
            }[];
            decision: components["schemas"]["PolicyDecision"];
        };
        /** ActionPreviewRequest */
        ActionPreviewRequest: {
            /** Context */
            context?: {
                [key: string]: string;
            };
            /**
             * Resource Intent
             * @default reflect
             */
            resource_intent: string;
            state: components["schemas"]["AffectiveState"];
            target: components["schemas"]["TargetState"];
        };
        /** ActivityCommandRequest */
        ActivityCommandRequest: {
            /**
             * Client Request Id
             * Format: uuid
             */
            client_request_id: string;
            /**
             * Command
             * @enum {string}
             */
            command: "start" | "pause" | "resume" | "finish_early" | "expire" | "stop" | "decline";
            /** Expected Conversation Revision */
            expected_conversation_revision: number;
            /** Expected Revision */
            expected_revision: number;
        };
        /**
         * ActivityConstraintInputs
         * @description Correctable activity limits; no free-form private text enters search context.
         */
        ActivityConstraintInputs: {
            /**
             * Avoid Breath Focus
             * @default false
             */
            avoid_breath_focus: boolean;
            /**
             * No Audio
             * @default false
             */
            no_audio: boolean;
            /**
             * No Video
             * @default false
             */
            no_video: boolean;
            /**
             * Seated
             * @default false
             */
            seated: boolean;
            /** Time Minutes */
            time_minutes?: number | null;
        };
        /** ActivityFollowUpRequest */
        ActivityFollowUpRequest: {
            /**
             * Client Request Id
             * Format: uuid
             */
            client_request_id: string;
            /** Expected Conversation Revision */
            expected_conversation_revision: number;
            /** Expected Revision */
            expected_revision: number;
        };
        /**
         * ActivityHistoryItem
         * @description One reported chat activity for the garden. It carries the person's own report
         *     choices only: no note, link, instructions or model text, and no claim of benefit.
         */
        ActivityHistoryItem: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Fit */
            fit: ("good" | "mixed" | "poor" | "unsure") | null;
            goal: components["schemas"]["Goal"] | null;
            /** Helpfulness */
            helpfulness: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Participation
             * @enum {string}
             */
            participation: "completed" | "partial" | "not_tried" | "stopped";
            /**
             * Reported At
             * Format: date-time
             */
            reported_at: string;
            /** State Change */
            state_change: ("toward_target" | "same" | "away_from_target" | "unsure") | null;
            /** Title */
            title: string;
        };
        /** ActivityHistoryPage */
        ActivityHistoryPage: {
            /** Items */
            items: components["schemas"]["ActivityHistoryItem"][];
        };
        /** ActivityReport */
        ActivityReport: {
            /** After Rating */
            after_rating?: number | null;
            /** Before Rating */
            before_rating?: number | null;
            /** Effort */
            effort?: number | null;
            /** Fit */
            fit?: ("good" | "mixed" | "poor" | "unsure") | null;
            /** Goal Progress */
            goal_progress?: ("closer" | "same" | "further" | "unsure") | null;
            /** Helpfulness */
            helpfulness?: number | null;
            /** Note */
            note?: string | null;
            /**
             * Participation
             * @enum {string}
             */
            participation: "completed" | "partial" | "not_tried" | "stopped";
            /** State Change */
            state_change?: ("toward_target" | "same" | "away_from_target" | "unsure") | null;
        };
        /** ActivityReportRequest */
        ActivityReportRequest: {
            /** After Rating */
            after_rating?: number | null;
            /** Before Rating */
            before_rating?: number | null;
            /**
             * Client Request Id
             * Format: uuid
             */
            client_request_id: string;
            /** Effort */
            effort?: number | null;
            /** Expected Conversation Revision */
            expected_conversation_revision: number;
            /** Expected Revision */
            expected_revision: number;
            /** Fit */
            fit?: ("good" | "mixed" | "poor" | "unsure") | null;
            /** Goal Progress */
            goal_progress?: ("closer" | "same" | "further" | "unsure") | null;
            /** Helpfulness */
            helpfulness?: number | null;
            /** Note */
            note?: string | null;
            /**
             * Participation
             * @enum {string}
             */
            participation: "completed" | "partial" | "not_tried" | "stopped";
            /** State Change */
            state_change?: ("toward_target" | "same" | "away_from_target" | "unsure") | null;
        };
        /**
         * ActivitySelectionProvenance
         * @description These are LLM/user choices, not randomized research-policy assignments.
         */
        ActivitySelectionProvenance: {
            /**
             * Eligible For Ope
             * @default false
             * @constant
             */
            eligible_for_ope: false;
            model_run?: components["schemas"]["ModelRun"] | null;
            /** Propensity */
            propensity?: null;
            /** Recommended Resource Id */
            recommended_resource_id: string;
            /** Selected Resource Id */
            selected_resource_id: string;
            /**
             * Selection Source
             * @enum {string}
             */
            selection_source: "llm" | "guided" | "user" | "search";
        };
        /** ActivitySession */
        ActivitySession: {
            /**
             * Check In Issued
             * @default false
             */
            check_in_issued: boolean;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Conversation Revision */
            conversation_revision?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Duration Seconds
             * @default 0
             */
            duration_seconds: number;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Final Follow Up
             * @default false
             */
            final_follow_up: boolean;
            /**
             * Follow Up Attempts
             * @default 0
             */
            follow_up_attempts: number;
            /** Follow Up Lease Until */
            follow_up_lease_until?: string | null;
            /** Follow Up Message Id */
            follow_up_message_id?: string | null;
            follow_up_model_run?: components["schemas"]["ModelRun"] | null;
            /** Follow Up Reply */
            follow_up_reply?: string | null;
            /** Follow Up Request Id */
            follow_up_request_id?: string | null;
            /**
             * Follow Up Status
             * @default none
             * @enum {string}
             */
            follow_up_status: "none" | "pending" | "generating" | "ready" | "failed";
            goal?: components["schemas"]["Goal"] | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Offered Message Id */
            offered_message_id?: string | null;
            /** Recommendation Reason */
            recommendation_reason?: string | null;
            /**
             * Remaining Seconds
             * @default 0
             */
            remaining_seconds: number;
            report?: components["schemas"]["ActivityReport"] | null;
            /** Reported At */
            reported_at?: string | null;
            resource: components["schemas"]["journalpulse__activity_models__ActivityResource"];
            /**
             * Revision
             * @default 0
             */
            revision: number;
            selection: components["schemas"]["ActivitySelectionProvenance"];
            /** Server Now */
            server_now?: string | null;
            /** Source Entry Id */
            source_entry_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** @default offered */
            status: components["schemas"]["ActivityStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * ActivityStatus
         * @enum {string}
         */
        ActivityStatus: "offered" | "active" | "paused" | "awaiting_report" | "completed" | "stopped" | "declined";
        /** AffectiveState */
        AffectiveState: {
            /** Agency */
            agency: number;
            /** Arousal */
            arousal: number;
            /** Confidence */
            confidence?: number | null;
            /** Derivation */
            derivation?: string | null;
            /** Emotion Tags */
            emotion_tags?: string[];
            /** Uncertainty */
            uncertainty?: string | null;
            /** Valence */
            valence: number;
        };
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Context */
            context?: {
                [key: string]: string;
            };
            /**
             * Llm Consent
             * @default false
             */
            llm_consent: boolean;
            /**
             * Locale
             * @default CA
             */
            locale: string;
            /** Text */
            text: string;
        };
        /** ChangeConversationPreferenceRequest */
        ChangeConversationPreferenceRequest: {
            /**
             * Client Request Id
             * Format: uuid
             */
            client_request_id: string;
            /** Expected Revision */
            expected_revision: number;
            /**
             * Preference
             * @enum {string}
             */
            preference: "listen" | "act";
        };
        /** Conversation */
        Conversation: {
            activity_card?: components["schemas"]["ActionCard"] | null;
            activity_constraints?: components["schemas"]["ActivityConstraintInputs"];
            activity_goal?: components["schemas"]["Goal"] | null;
            /**
             * Activity Move
             * @default reflect
             * @enum {string}
             */
            activity_move: "reflect" | "clarify" | "propose" | "negotiate" | "outcome" | "pause";
            /** Activity Search Topic */
            activity_search_topic?: string | null;
            card?: components["schemas"]["ActionCard"] | null;
            /** Confirmed Feelings */
            confirmed_feelings?: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Feelings */
            feelings?: string[];
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** @default auto */
            interaction_preference: components["schemas"]["InteractionPreference"];
            /** Llm Consent */
            llm_consent: boolean;
            /** Locale */
            locale: string;
            /** @default ai */
            mode: components["schemas"]["ConversationMode"];
            /** Prompt Version */
            prompt_version: string;
            /**
             * Ready For Action
             * @default false
             */
            ready_for_action: boolean;
            /** Reflection Id */
            reflection_id?: string | null;
            /** Reported Mood */
            reported_mood?: number | null;
            /**
             * Retain Text
             * @default false
             */
            retain_text: boolean;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            safety?: components["schemas"]["SafetyResult"] | null;
            /** @default normal */
            safety_mode: components["schemas"]["SafetyMode"];
            /** Source Entry Created At */
            source_entry_created_at?: string | null;
            /** Source Entry Id */
            source_entry_id?: string | null;
            /** @default open */
            status: components["schemas"]["ConversationStatus"];
            /** Summary */
            summary?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ConversationDetail */
        ConversationDetail: {
            conversation: components["schemas"]["Conversation"];
            /** Messages */
            messages: components["schemas"]["ConversationMessage"][];
        };
        /** ConversationMessage */
        ConversationMessage: {
            /** Client Message Id */
            client_message_id?: string | null;
            /** Content */
            content?: string | null;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            model_run?: components["schemas"]["ModelRun"] | null;
            request_inputs?: components["schemas"]["ConversationRequestInputs"] | null;
            role: components["schemas"]["MessageRole"];
            safety_mode: components["schemas"]["SafetyMode"];
        };
        /**
         * ConversationMode
         * @enum {string}
         */
        ConversationMode: "ai" | "guided";
        /**
         * ConversationRequestInputs
         * @description Explicit taps accompanying a turn; no text or text digest is retained here.
         */
        ConversationRequestInputs: {
            /** Confirmed Feelings */
            confirmed_feelings?: string[] | null;
            goal?: components["schemas"]["Goal"] | null;
            /** Mood Score */
            mood_score?: number | null;
        };
        /**
         * ConversationStatus
         * @enum {string}
         */
        ConversationStatus: "open" | "closed";
        /** ConversationTurnRequest */
        ConversationTurnRequest: {
            /**
             * Client Message Id
             * Format: uuid
             */
            client_message_id: string;
            /** Confirmed Feelings */
            confirmed_feelings?: string[] | null;
            goal?: components["schemas"]["Goal"] | null;
            /** Mood Score */
            mood_score?: number | null;
            /** Text */
            text: string;
        };
        /** ConversationTurnResult */
        ConversationTurnResult: {
            assistant_message: components["schemas"]["ConversationMessage"];
            conversation: components["schemas"]["Conversation"];
            user_message: components["schemas"]["ConversationMessage"];
        };
        /** CreateActivitySessionRequest */
        CreateActivitySessionRequest: {
            /**
             * Client Request Id
             * Format: uuid
             */
            client_request_id: string;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Expected Conversation Revision */
            expected_conversation_revision: number;
            /** Resource Id */
            resource_id: string;
            /** Resource Token */
            resource_token?: string | null;
        };
        /** CreateJournalEntryRequest */
        CreateJournalEntryRequest: {
            /** Client Request Id */
            client_request_id?: string | null;
            /** Text */
            text: string;
        };
        /** DeletionResponse */
        DeletionResponse: {
            /**
             * Auth Identity Deleted
             * @default false
             */
            auth_identity_deleted: boolean;
            /** Deleted Records */
            deleted_records: number;
            /**
             * Note
             * @default Journal data was deleted. Your sign-in identity remains active.
             */
            note: string;
        };
        /** DiscoveryCandidate */
        DiscoveryCandidate: {
            /** Description */
            description: string;
            /**
             * Evidence Kind
             * @default search_snippet
             * @constant
             */
            evidence_kind: "search_snippet";
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Why Selected */
            why_selected: string;
        };
        /** DiscoveryProvenance */
        DiscoveryProvenance: {
            /** Candidate Count */
            candidate_count: number;
            /** Model Runs */
            model_runs: components["schemas"]["ModelRun"][];
            /**
             * Page Fetches
             * @default 0
             * @constant
             */
            page_fetches: 0;
            /** Prompt Version */
            prompt_version: string;
            /** Retrieved At */
            retrieved_at: string;
            /**
             * Search Calls
             * @default 1
             * @constant
             */
            search_calls: 1;
            /**
             * Search Provider
             * @default brave
             * @constant
             */
            search_provider: "brave";
        };
        /** DiscoveryRequest */
        DiscoveryRequest: {
            /** Excluded Urls */
            excluded_urls?: string[];
            /** Feedback */
            feedback?: string | null;
            /**
             * Llm Consent
             * @default false
             */
            llm_consent: boolean;
            /**
             * Locale
             * @default CA
             */
            locale: string;
            /** Original Query */
            original_query: string;
            /** Previous Query */
            previous_query?: string | null;
        };
        /** DiscoveryResponse */
        DiscoveryResponse: {
            /** Candidates */
            candidates: components["schemas"]["DiscoveryCandidate"][];
            /** Limitations */
            limitations: string[];
            /** Original Query */
            original_query: string;
            provenance: components["schemas"]["DiscoveryProvenance"];
            /** Updated Query */
            updated_query: string;
        };
        /**
         * GenerationErrorResponse
         * @description 422 can carry a provider-decline message or FastAPI input-validation details.
         */
        GenerationErrorResponse: {
            /** Detail */
            detail: string | {
                [key: string]: unknown;
            }[];
        };
        /**
         * Goal
         * @enum {string}
         */
        Goal: "settle" | "move" | "understand" | "connect" | "act";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InlineDiscoveryRequest */
        InlineDiscoveryRequest: {
            constraints?: components["schemas"]["ActivityConstraintInputs"] | null;
            /** Excluded Urls */
            excluded_urls?: string[];
            /** Expected Revision */
            expected_revision: number;
            /** Feedback */
            feedback?: string | null;
            goal?: components["schemas"]["Goal"] | null;
            /**
             * Llm Consent
             * @default false
             */
            llm_consent: boolean;
            /** Original Query */
            original_query?: string | null;
            /** Previous Query */
            previous_query?: string | null;
            /**
             * Style
             * @default ground
             * @enum {string}
             */
            style: "ground" | "move" | "connect" | "reflect" | "play" | "watch" | "read" | "pause";
        };
        /** InlineDiscoveryResponse */
        InlineDiscoveryResponse: {
            /** Candidates */
            candidates: components["schemas"]["DiscoveryCandidate"][];
            /** Conversation Revision */
            conversation_revision: number;
            /** Limitations */
            limitations: string[];
            /** Offers */
            offers: components["schemas"]["InlineResourceOffer"][];
            /** Original Query */
            original_query: string;
            provenance: components["schemas"]["DiscoveryProvenance"];
            /** Updated Query */
            updated_query: string;
        };
        /** InlineResourceOffer */
        InlineResourceOffer: {
            resource: components["schemas"]["journalpulse__activity_resources__ActivityResource"];
            /** Resource Token */
            resource_token: string;
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Action Counts */
            action_counts: {
                [key: string]: number;
            };
            /** Average Helpfulness By Action */
            average_helpfulness_by_action: {
                [key: string]: number;
            };
            /** Average State Change */
            average_state_change: {
                [key: string]: number;
            } | null;
            /** Completed Outcomes */
            completed_outcomes: number;
            /** Completion Rate */
            completion_rate: number;
            /**
             * Note
             * @default These are descriptive personal patterns, not causal or clinical conclusions.
             */
            note: string;
            /** Pending Decision Ids */
            pending_decision_ids: string[];
            /** Reflection Count */
            reflection_count: number;
            /** State Trajectory */
            state_trajectory: components["schemas"]["StatePoint"][];
        };
        /**
         * InteractionPreference
         * @description An explicit choice for this chat, independent of AI/guided provider mode.
         * @enum {string}
         */
        InteractionPreference: "auto" | "listen" | "act";
        /**
         * JournalEntry
         * @description An immutable saved entry; AI output is never folded into its source text.
         */
        JournalEntry: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Text */
            text: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** JournalEntryPage */
        JournalEntryPage: {
            /** Items */
            items: components["schemas"]["JournalEntry"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * JournalReflectionResult
         * @description A transient reflection. Deleting or exporting the source has no AI row to retain.
         */
        JournalReflectionResult: {
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /**
             * Generated Text Retained
             * @default false
             * @constant
             */
            generated_text_retained: false;
            model_run: components["schemas"]["ModelRun"];
            /** Reply */
            reply: string;
            safety: components["schemas"]["SafetyResult"];
        };
        /**
         * MessageRole
         * @enum {string}
         */
        MessageRole: "user" | "assistant";
        /** ModelRun */
        ModelRun: {
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Fallback Reason */
            fallback_reason?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * Provider
             * @default openrouter
             */
            provider: string;
            /** Schema Valid */
            schema_valid: boolean;
            /** Skill Hash */
            skill_hash?: string | null;
            /** Skill Version */
            skill_version?: string | null;
            /**
             * Used Fallback
             * @default false
             */
            used_fallback: boolean;
        };
        /** OutcomePage */
        OutcomePage: {
            /** Items */
            items: components["schemas"]["OutcomeRecord"][];
        };
        /** OutcomeRecord */
        OutcomeRecord: {
            /** Completed */
            completed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** Effort */
            effort?: number | null;
            /** Elapsed Minutes */
            elapsed_minutes?: number | null;
            /** Helpfulness */
            helpfulness?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Note */
            note?: string | null;
            post_state?: components["schemas"]["AffectiveState"] | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** OutcomeRequest */
        OutcomeRequest: {
            /** Client Request Id */
            client_request_id?: string | null;
            /** Completed */
            completed: boolean;
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** Effort */
            effort?: number | null;
            /** Elapsed Minutes */
            elapsed_minutes?: number | null;
            /** Helpfulness */
            helpfulness?: number | null;
            /** Note */
            note?: string | null;
            post_state?: components["schemas"]["AffectiveState"] | null;
        };
        /** PolicyDecision */
        PolicyDecision: {
            /** Action Id */
            action_id: string;
            /** Context Snapshot */
            context_snapshot: {
                [key: string]: unknown;
            };
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id?: string;
            /**
             * Eligible For Ope
             * @default true
             */
            eligible_for_ope: boolean;
            /** Explanation */
            explanation: string;
            /** Policy Name */
            policy_name: string;
            /** Policy Version */
            policy_version: string;
            /** Propensity */
            propensity?: number | null;
            /** Recommended Action Id */
            recommended_action_id?: string | null;
            /** Safe Action Ids */
            safe_action_ids: string[];
            /** @default policy */
            selection_source: components["schemas"]["SelectionSource"];
        };
        /** PreparedAnalysis */
        PreparedAnalysis: {
            model_run: components["schemas"]["ModelRun"];
            reflection: components["schemas"]["ReflectionCopy"];
            /** Resource Intent */
            resource_intent: string;
            safety: components["schemas"]["SafetyResult"];
            state: components["schemas"]["AffectiveState"];
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Checks */
            checks: {
                [key: string]: string;
            };
            /** Status */
            status: string;
        };
        /** ReflectJournalEntryRequest */
        ReflectJournalEntryRequest: {
            /** Llm Consent */
            llm_consent: boolean;
            /**
             * Locale
             * @default CA
             */
            locale: string;
        };
        /** ReflectionCopy */
        ReflectionCopy: {
            /** Interpretation */
            interpretation: string;
            /** Reflection Question */
            reflection_question: string;
            /** Summary */
            summary: string;
        };
        /** ReflectionPage */
        ReflectionPage: {
            /** Items */
            items: components["schemas"]["ReflectionRecord"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ReflectionRecord */
        ReflectionRecord: {
            /** Context */
            context?: {
                [key: string]: string;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            decision: components["schemas"]["PolicyDecision"];
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            model_run?: components["schemas"]["ModelRun"] | null;
            reflection: components["schemas"]["ReflectionCopy"];
            safety: components["schemas"]["SafetyResult"];
            self_report_input?: components["schemas"]["SelfReportInput"] | null;
            state: components["schemas"]["AffectiveState"];
            target: components["schemas"]["TargetState"];
            /** Text */
            text?: string | null;
            /**
             * Text Retained
             * @default false
             */
            text_retained: boolean;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ReflectionRequest */
        ReflectionRequest: {
            /** Chosen Action Id */
            chosen_action_id?: string | null;
            /** Client Request Id */
            client_request_id?: string | null;
            /** Context */
            context?: {
                [key: string]: string;
            };
            /**
             * Llm Consent
             * @default false
             */
            llm_consent: boolean;
            /**
             * Locale
             * @default CA
             */
            locale: string;
            prepared_analysis?: components["schemas"]["PreparedAnalysis"] | null;
            /** Retain Text */
            retain_text?: boolean | null;
            self_report?: components["schemas"]["AffectiveState"] | null;
            target: components["schemas"]["TargetState"];
            /** Text */
            text: string;
        };
        /**
         * SafetyMode
         * @enum {string}
         */
        SafetyMode: "normal" | "support";
        /** SafetyResult */
        SafetyResult: {
            /** Exploration Allowed */
            exploration_allowed: boolean;
            /** Locale */
            locale: string;
            mode: components["schemas"]["SafetyMode"];
            /** Reasons */
            reasons?: string[];
            /** Resource Ids */
            resource_ids?: string[];
            /** Support Message */
            support_message?: string | null;
        };
        /**
         * SelectionSource
         * @enum {string}
         */
        SelectionSource: "policy" | "policy_accepted" | "user_override";
        /**
         * SelfReportInput
         * @description Exactly what the person tapped. The AffectiveState on a record is derived from it.
         */
        SelfReportInput: {
            /** Feelings */
            feelings?: string[];
            /** Mood Score */
            mood_score?: number | null;
        };
        /** StartConversationRequest */
        StartConversationRequest: {
            /** Client Request Id */
            client_request_id?: string | null;
            /**
             * Llm Consent
             * @default false
             */
            llm_consent: boolean;
            /**
             * Locale
             * @default CA
             */
            locale: string;
            /**
             * Retain Text
             * @default false
             */
            retain_text: boolean;
            /** Source Entry Id */
            source_entry_id?: string | null;
        };
        /** StatePoint */
        StatePoint: {
            /** Agency */
            agency: number;
            /** Arousal */
            arousal: number;
            /** Created At */
            created_at: string;
            /**
             * Reflection Id
             * Format: uuid
             */
            reflection_id: string;
            /** Valence */
            valence: number;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /** Analysis Mode */
            analysis_mode: string;
            /** Message */
            message: string;
            /** Persistence Mode */
            persistence_mode: string;
        };
        /** TargetState */
        TargetState: {
            /** Agency */
            agency?: number | null;
            /** Arousal */
            arousal?: number | null;
            /** Goal */
            goal: string;
            /** Valence */
            valence?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ActivityResource
         * @description A server-approved descriptor. Search provenance never implies page review.
         */
        journalpulse__activity_models__ActivityResource: {
            discovery_provenance?: components["schemas"]["DiscoveryProvenance"] | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Format
             * @enum {string}
             */
            format: "timer" | "external" | "manual";
            /** Id */
            id: string;
            /** Instructions */
            instructions?: string[];
            /**
             * Kind
             * @enum {string}
             */
            kind: "meditation" | "movement" | "reflection" | "connection" | "focus" | "video" | "reading" | "other";
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "builtin" | "catalog" | "search_snippet";
            /**
             * Provider
             * @default JournalPulse
             */
            provider: string;
            /**
             * Resource Type
             * @default activity
             */
            resource_type: string;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
        };
        /** ActivityResource */
        journalpulse__activity_resources__ActivityResource: {
            /**
             * Breath Focus
             * @default false
             */
            breath_focus: boolean;
            /**
             * Coping Style
             * @enum {string}
             */
            coping_style: "watch" | "move" | "read" | "play" | "connect" | "ground" | "reflect";
            discovery_provenance?: components["schemas"]["DiscoveryProvenance"] | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Emotion Tags */
            emotion_tags?: string[];
            /**
             * Evidence Kind
             * @enum {string}
             */
            evidence_kind: "app_guidance" | "catalog_review" | "search_snippet";
            /** Goal Tags */
            goal_tags?: string[];
            /** Id */
            id: string;
            /** Instructions */
            instructions?: string[];
            /**
             * Kind
             * @enum {string}
             */
            kind: "meditation" | "movement" | "reading" | "video" | "social" | "play" | "reflection" | "focus";
            /**
             * No Audio
             * @default false
             */
            no_audio: boolean;
            /**
             * No Video
             * @default false
             */
            no_video: boolean;
            /** Provider */
            provider: string;
            /**
             * Resource Type
             * @enum {string}
             */
            resource_type: "activity" | "video" | "website" | "game";
            /** Reviewed At */
            reviewed_at?: string | null;
            /**
             * Seated
             * @default false
             */
            seated: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "builtin" | "catalog" | "search_snippet";
            /** Source Tier */
            source_tier?: string | null;
            /** Summary */
            summary: string;
            /**
             * Timer Enabled
             * @default false
             */
            timer_enabled: boolean;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            /** Why Selected */
            why_selected?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    delete_account_data_v1_account_data_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_actions_v1_actions_preview_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_history_v1_activity_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityHistoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_activity_v1_activity_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    control_activity_v1_activity_sessions__session_id__commands_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    follow_up_activity_v1_activity_sessions__session_id__follow_up_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityFollowUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_activity_v1_activity_sessions__session_id__report_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_conversation_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_conversation_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_card_v1_conversations__conversation_id__accept_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_activity_v1_conversations__conversation_id__activity_sessions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySession"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    offer_activity_v1_conversations__conversation_id__activity_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivitySessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_conversation_v1_conversations__conversation_id__close_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_v1_conversations__conversation_id__discover_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InlineDiscoveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InlineDiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_conversation_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationTurnResult"];
                };
            };
            /** @description Invalid input or provider decline */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationErrorResponse"];
                };
            };
        };
    };
    change_preference_v1_conversations__conversation_id__preference_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeConversationPreferenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_resources_v1_discovery_search_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResponse"];
                };
            };
            /** @description Invalid input, support routing, or provider decline */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationErrorResponse"];
                };
            };
        };
    };
    export_v1_export_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insights_v1_insights_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_v1_journal_entries_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry_v1_journal_entries_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJournalEntryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_entry_v1_journal_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_v1_journal_entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reflect_entry_v1_journal_entries__entry_id__reflect_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReflectJournalEntryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalReflectionResult"];
                };
            };
            /** @description Invalid input or provider decline */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationErrorResponse"];
                };
            };
        };
    };
    outcomes_v1_outcomes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_outcome_v1_outcomes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reflections_v1_reflections_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reflection_v1_reflections_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReflectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_reflection_v1_reflections_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreparedAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reflection_v1_reflections__reflection_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path: {
                reflection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resources_v1_resources_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_status_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-JournalPulse-User"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
